"""initial tables

Revision ID: 9fc6d2130eb1
Revises: 
Create Date: 2026-09-21 02:58:57.012096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9fc6d2130eb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_pass', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('links',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('short_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('long_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_links_custom_alias'), 'links', ['custom_alias'], unique=True)
    op.create_index(op.f('ix_links_short_code'), 'links', ['short_code'], unique=True)
    op.create_table('click_logs',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('links_uid', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('referer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['links_uid'], ['links.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_click_logs_links_uid'), 'click_logs', ['links_uid'], unique=False)
    op.create_index(op.f('ix_click_logs_timestamp'), 'click_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_logs_timestamp'), table_name='click_logs')
    op.drop_index(op.f('ix_click_logs_links_uid'), table_name='click_logs')
    op.drop_table('click_logs')
    op.drop_index(op.f('ix_links_short_code'), table_name='links')
    op.drop_index(op.f('ix_links_custom_alias'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
