"""drop custom_alias column

Revision ID: ac8cc9f69111
Revises: eb4ec235c8ee
Create Date: 2026-10-02 19:23:06.894577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac8cc9f69111'
down_revision: Union[str, Sequence[str], None] = 'eb4ec235c8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_custom_alias'), table_name='links')
    op.drop_column('links', 'custom_alias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('custom_alias', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_links_custom_alias'), 'links', ['custom_alias'], unique=True)
    # ### end Alembic commands ###
