"""rename long_link to long_url

Revision ID: eb4ec235c8ee
Revises: 9fc6d2130eb1
Create Date: 2026-09-24 20:07:48.612863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb4ec235c8ee'
down_revision: Union[str, Sequence[str], None] = '9fc6d2130eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'long_link', new_column_name='long_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'long_url', new_column_name='long_link')
    # ### end Alembic commands ###
